### PR TITLE
Point cloud utility functions for mujoco [Draft]

### PR DESCRIPTION
**Pull request by Wenxuan-Zhou**
Ongoing

### CODE REVIEW

**Comment by vikashplus** [comment]
@Wenxuan-Zhou we received a request for point cloud support in RoboHive. It will be great to develop and get this feature integrated. 
https://github.com/vikashplus/robohive/issues/116

**Comment by Wenxuan-Zhou** [comment]
Will work on this as soon as possible!

**Comment by Wenxuan-Zhou** [comment]
I have updated the code and provided an example in the colab. 
I noticed that the depth image is upside-down compared to rgb. Is there any reason for that? @vikashplus

**Comment by vikashplus** [comment]
IIRC it was upside down in MuJoCo_py. So it might be a stale rationale that needs an update for new official wrappers. [This is the line](https://github.com/vikashplus/robohive/blob/main/robohive/renderer/mj_renderer.py#L117) where it happens. Feel free to test and add the fix to your PR.

**Comment by Wenxuan-Zhou** [comment]
I have commented out the line you mentioned and verified the output. It should be ready to merge!

**Comment by shivakanthsujit** [comment]
Hello,

I am using these files and they work out of the box with the current robohive version. Could this PR be merged into main?

**Comment by vikashplus** [comment]
@shivakanthsujit -- mered into `dev`. It will go out with the next release.

**Pull request merged**
