### PR TITLE
Update import_utils.py

### PR DESCRIPTION
**Pull request by Vittorio-Caggiano**
add an explicit call to `importlib.util` to make it compatible with macos

### CODE REVIEW

**Comment by Vittorio-Caggiano** [comment]
fyi, I use an M1 / MacAir

**Comment by vikashplus** [comment]
Unlikely that hardware specs should matter, right?

**Comment by Vittorio-Caggiano** [comment]
not sure.. but it seems to be also an [issue in python 3.11](https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641)

**Comment by vikashplus** [comment]
This is likely because of the python version. I'm using 3.8. @Vittorio-Caggiano  -- what are you using?

**Comment by Vittorio-Caggiano** [comment]
tested with python 3.9 and 3.10

**Pull request closed without merging**
